// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProblemPayload>>
abstract class ProblemPayload implements RustOpaqueInterface {}

abstract class OptimizationSolver {
  Future<void> name();

  Future<SolverSolution> solve({required ProblemPayload payload});

  Future<bool> supportsMilp();
}

class SolverSolution {
  final int statusCode;
  final double objectiveValue;
  final Float64List variableValues;
  final Float64List dualValues;

  const SolverSolution({
    required this.statusCode,
    required this.objectiveValue,
    required this.variableValues,
    required this.dualValues,
  });

  @override
  int get hashCode =>
      statusCode.hashCode ^
      objectiveValue.hashCode ^
      variableValues.hashCode ^
      dualValues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SolverSolution &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          objectiveValue == other.objectiveValue &&
          variableValues == other.variableValues &&
          dualValues == other.dualValues;
}
